### ISSUE TITLE
Modify type of self.Symbols in datawell.iex

### ISSUE THREAD

**Issue by nikolai-riabinin-epam** [petelind/ConsumingAPI#16]
**Is your feature request related to a problem? Please describe.**
When we update a small amount of symbols, you need to iterate over all list to find what you need.
example: ```[{'symbol': 'XLMUSDT', 'date': '2020-02-06', 'isEnabled': True}
{'symbol': 'QTUMUSDT', 'date': '2020-02-06', 'isEnabled': True}]```

**Describe the solution you'd like**
Function get_stocks return dict with symbol key.
example: ```{
    "XLMUSDT": {
        "symbol": {
            "date": "2020-02-06",
            "isEnabled": "True"
        }
    },
    "QTUMUSDT": {
        "symbol": {
            "date": "2020-02-06",
            "isEnabled": "True"
        }
    }
}```

**Comment by dostoevskoy** [comment]
Changes have been applied with pull #17

**Comment by nikolai-riabinin-epam** [comment]
Fixed by #17
