### ISSUE TITLE
Pull COMPANY profile from the datasource

### ISSUE THREAD

**Issue by petelind** [petelind/ConsumingAPI#2]
Add a method for IEX which will populate COMPANY data either for all stocks (if no ticker given) or a particular stock (if ticker given). Here is API endpoint data:
https://iexcloud.io/docs/api/#company

**Comment by dostoevskoy** [comment]
Initial changes have been added with the commit 56f2c2b . 
I've added a new method *getCompany* and new parameter *companyList* to the class Iex.
