### ISSUE TITLE
Implement table cleanup for dynamo

### ISSUE THREAD

**Issue by petelind** [petelind/ConsumingAPI#21]
def clean_table(self, symbols_to_remove: list):
        """
        Use this one to either clean specific stocks from the db or clean up the db if its small.
        :param symbols_to_remove: list of dicts each containing 'symbol' string
        :returns: number of the elements removed as int, 0 if not found, AppException if AWS Error: No access etc
        """

**Comment by petelind** [comment]
Please add exception handling, and take into account that at some point you'll hit throttling limit.

**Comment by AliaksandrMakavetskiTR** [comment]
Completed
