### ISSUE TITLE
Implement empty string removal (util method) from the dicts to they can be stored to the Dynamo

### ISSUE THREAD

**Issue by petelind** [petelind/ConsumingAPI#22]
def remove_empty_strings(dict_to_clean: dict):
        """
        Removes all the empty key+value pairs from the dict you give it; use to clean up dicts before persisting them to the DynamoDB
        :param dict_to_clean: as dict()
        :return: only non-empty key+value pairs from the source dict as dict()

**Comment by NikopolosHub** [comment]
The method has been implemented.
