### ISSUE TITLE
Implement document retrieval for Dynamo persistence layer

### ISSUE THREAD

**Issue by petelind** [petelind/ConsumingAPI#23]
def get_filtered_documents(self, symbol_to_find: str = None, target_date: datetime.date = None):
        """
        Returns a list of documents matching given ticker and/or date
        :param symbol_to_find: ticker as a string
        :param target_date: desired date as a datetime.date, leave empty to get for all available dates
        :return: a list of dicts() each containing data available for a stock for a given period of time
        """

**Comment by petelind** [comment]
@dostoevskoy how its going? Forgot to push or need help with something?

**Comment by dostoevskoy** [comment]
I spent additional time to dive into the code and to learn how it works exactly.
