### ISSUE TITLE
Self-generating create table method

### ISSUE THREAD

**Issue by petelind** [petelind/ConsumingAPI#25]
When the store is instantiated - check if such Dynamo DB table exists.
If it does not exist - try to create the table given the credentials, region, and table name in the env. variables (see app package for details).
If you cant create - log ClientError and all details and terminate.

**Comment by aprotsik** [comment]
When the class instance is created, it should immediately check for an existing DynamoDB table and create it if it doesn't exist so when any method that operates data in Dynamo is called, table is guaranteed present, correct?
